services:
  auth-service-db:
    container_name: postgres-auth-service
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB_AUTH}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d ${POSTGRES_DB_AUTH}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service-db:
    container_name: postgres-users-service
    image: postgres:18
    environment:
      POSTGRES_DB: ${POSTGRES_DB_USERS}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5434:5432'
    volumes:
      - users_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d ${POSTGRES_DB_USERS}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - auth-service-db
      - user-service-db

volumes:
  postgres_data:
  pgadmin_data:
  users_data:
